# Generated by Django 3.1.3 on 2020-11-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название еды')),
                ('image', models.ImageField(blank=True, null=True, upload_to='foods', verbose_name='Изображение')),
                ('price', models.PositiveSmallIntegerField(default=0, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание еды')),
                ('category', models.ManyToManyField(blank=True, null=True, related_name='food_category', to='foods.FoodCategory', verbose_name='Категорий')),
            ],
        ),
    ]
