# Generated by Django 3.1.3 on 2020-11-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_auto_20201130_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='food_category', to='foods.FoodCategory', verbose_name='Категорий'),
        ),
    ]
