# Generated by Django 3.1.3 on 2020-12-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_auto_20201130_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='image',
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='main_title',
            field=models.CharField(db_index=True, default=1, max_length=255, verbose_name='Название меню'),
            preserve_default=False,
        ),
    ]
