# Generated by Django 3.1.3 on 2020-11-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название место')),
                ('location', models.CharField(max_length=255, verbose_name='Место расположения')),
                ('check', models.CharField(max_length=255, verbose_name='Средний счет')),
                ('seats', models.PositiveIntegerField(default=0, verbose_name='Количество мест')),
                ('food', models.ManyToManyField(blank=True, null=True, related_name='department_food', to='foods.FoodCategory', verbose_name='Кухня')),
            ],
        ),
    ]
