# Generated by Django 3.1.3 on 2020-12-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departmants', '0002_auto_20201203_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='department',
            name='facebook_profile',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка на Facebook'),
        ),
        migrations.AddField(
            model_name='department',
            name='insta_profile',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка на Instagram'),
        ),
        migrations.AddField(
            model_name='department',
            name='web_profile',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка на Website'),
        ),
    ]
