# Generated by Django 3.1.3 on 2020-12-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departmants', '0004_remove_department_phone_of_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='department', verbose_name='Изображение заведения'),
        ),
    ]
