# Generated by Django 3.1.3 on 2020-12-03 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departmants', '0006_phonenumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='phonenumber',
            options={'ordering': ('-id',)},
        ),
    ]
